// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: object_detection/protos/square_box_coder.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fsquare_5fbox_5fcoder_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fsquare_5fbox_5fcoder_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3018000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3018000 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_object_5fdetection_2fprotos_2fsquare_5fbox_5fcoder_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_object_5fdetection_2fprotos_2fsquare_5fbox_5fcoder_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxiliaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[1]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_object_5fdetection_2fprotos_2fsquare_5fbox_5fcoder_2eproto;
namespace object_detection {
namespace protos {
class SquareBoxCoder;
struct SquareBoxCoderDefaultTypeInternal;
extern SquareBoxCoderDefaultTypeInternal _SquareBoxCoder_default_instance_;
}  // namespace protos
}  // namespace object_detection
PROTOBUF_NAMESPACE_OPEN
template<> ::object_detection::protos::SquareBoxCoder* Arena::CreateMaybeMessage<::object_detection::protos::SquareBoxCoder>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace object_detection {
namespace protos {

// ===================================================================

class SquareBoxCoder final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:object_detection.protos.SquareBoxCoder) */ {
 public:
  inline SquareBoxCoder() : SquareBoxCoder(nullptr) {}
  ~SquareBoxCoder() override;
  explicit constexpr SquareBoxCoder(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  SquareBoxCoder(const SquareBoxCoder& from);
  SquareBoxCoder(SquareBoxCoder&& from) noexcept
    : SquareBoxCoder() {
    *this = ::std::move(from);
  }

  inline SquareBoxCoder& operator=(const SquareBoxCoder& from) {
    CopyFrom(from);
    return *this;
  }
  inline SquareBoxCoder& operator=(SquareBoxCoder&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>(::PROTOBUF_NAMESPACE_ID::UnknownFieldSet::default_instance);
  }
  inline ::PROTOBUF_NAMESPACE_ID::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::PROTOBUF_NAMESPACE_ID::UnknownFieldSet>();
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const SquareBoxCoder& default_instance() {
    return *internal_default_instance();
  }
  static inline const SquareBoxCoder* internal_default_instance() {
    return reinterpret_cast<const SquareBoxCoder*>(
               &_SquareBoxCoder_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(SquareBoxCoder& a, SquareBoxCoder& b) {
    a.Swap(&b);
  }
  inline void Swap(SquareBoxCoder* other) {
    if (other == this) return;
    if (GetOwningArena() == other->GetOwningArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(SquareBoxCoder* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline SquareBoxCoder* New() const final {
    return new SquareBoxCoder();
  }

  SquareBoxCoder* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<SquareBoxCoder>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const SquareBoxCoder& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom(const SquareBoxCoder& from);
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message* to, const ::PROTOBUF_NAMESPACE_ID::Message& from);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(SquareBoxCoder* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "object_detection.protos.SquareBoxCoder";
  }
  protected:
  explicit SquareBoxCoder(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLengthScaleFieldNumber = 3,
    kYScaleFieldNumber = 1,
    kXScaleFieldNumber = 2,
  };
  // optional float length_scale = 3 [default = 5];
  bool has_length_scale() const;
  private:
  bool _internal_has_length_scale() const;
  public:
  void clear_length_scale();
  float length_scale() const;
  void set_length_scale(float value);
  private:
  float _internal_length_scale() const;
  void _internal_set_length_scale(float value);
  public:

  // optional float y_scale = 1 [default = 10];
  bool has_y_scale() const;
  private:
  bool _internal_has_y_scale() const;
  public:
  void clear_y_scale();
  float y_scale() const;
  void set_y_scale(float value);
  private:
  float _internal_y_scale() const;
  void _internal_set_y_scale(float value);
  public:

  // optional float x_scale = 2 [default = 10];
  bool has_x_scale() const;
  private:
  bool _internal_has_x_scale() const;
  public:
  void clear_x_scale();
  float x_scale() const;
  void set_x_scale(float value);
  private:
  float _internal_x_scale() const;
  void _internal_set_x_scale(float value);
  public:

  // @@protoc_insertion_point(class_scope:object_detection.protos.SquareBoxCoder)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::internal::HasBits<1> _has_bits_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  float length_scale_;
  float y_scale_;
  float x_scale_;
  friend struct ::TableStruct_object_5fdetection_2fprotos_2fsquare_5fbox_5fcoder_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// SquareBoxCoder

// optional float y_scale = 1 [default = 10];
inline bool SquareBoxCoder::_internal_has_y_scale() const {
  bool value = (_has_bits_[0] & 0x00000002u) != 0;
  return value;
}
inline bool SquareBoxCoder::has_y_scale() const {
  return _internal_has_y_scale();
}
inline void SquareBoxCoder::clear_y_scale() {
  y_scale_ = 10;
  _has_bits_[0] &= ~0x00000002u;
}
inline float SquareBoxCoder::_internal_y_scale() const {
  return y_scale_;
}
inline float SquareBoxCoder::y_scale() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SquareBoxCoder.y_scale)
  return _internal_y_scale();
}
inline void SquareBoxCoder::_internal_set_y_scale(float value) {
  _has_bits_[0] |= 0x00000002u;
  y_scale_ = value;
}
inline void SquareBoxCoder::set_y_scale(float value) {
  _internal_set_y_scale(value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SquareBoxCoder.y_scale)
}

// optional float x_scale = 2 [default = 10];
inline bool SquareBoxCoder::_internal_has_x_scale() const {
  bool value = (_has_bits_[0] & 0x00000004u) != 0;
  return value;
}
inline bool SquareBoxCoder::has_x_scale() const {
  return _internal_has_x_scale();
}
inline void SquareBoxCoder::clear_x_scale() {
  x_scale_ = 10;
  _has_bits_[0] &= ~0x00000004u;
}
inline float SquareBoxCoder::_internal_x_scale() const {
  return x_scale_;
}
inline float SquareBoxCoder::x_scale() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SquareBoxCoder.x_scale)
  return _internal_x_scale();
}
inline void SquareBoxCoder::_internal_set_x_scale(float value) {
  _has_bits_[0] |= 0x00000004u;
  x_scale_ = value;
}
inline void SquareBoxCoder::set_x_scale(float value) {
  _internal_set_x_scale(value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SquareBoxCoder.x_scale)
}

// optional float length_scale = 3 [default = 5];
inline bool SquareBoxCoder::_internal_has_length_scale() const {
  bool value = (_has_bits_[0] & 0x00000001u) != 0;
  return value;
}
inline bool SquareBoxCoder::has_length_scale() const {
  return _internal_has_length_scale();
}
inline void SquareBoxCoder::clear_length_scale() {
  length_scale_ = 5;
  _has_bits_[0] &= ~0x00000001u;
}
inline float SquareBoxCoder::_internal_length_scale() const {
  return length_scale_;
}
inline float SquareBoxCoder::length_scale() const {
  // @@protoc_insertion_point(field_get:object_detection.protos.SquareBoxCoder.length_scale)
  return _internal_length_scale();
}
inline void SquareBoxCoder::_internal_set_length_scale(float value) {
  _has_bits_[0] |= 0x00000001u;
  length_scale_ = value;
}
inline void SquareBoxCoder::set_length_scale(float value) {
  _internal_set_length_scale(value);
  // @@protoc_insertion_point(field_set:object_detection.protos.SquareBoxCoder.length_scale)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)

}  // namespace protos
}  // namespace object_detection

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_object_5fdetection_2fprotos_2fsquare_5fbox_5fcoder_2eproto
